<script>
	import { browser } from '$app/environment';
	import Button from '$lib/components/Button.svelte';
	import Footer from '$lib/components/Footer.svelte';

	import { getCookie, setCookie } from '$lib/utils/cookies';
	import spotify, { saveSpotifyUser, spotifyUser } from '$lib/utils/spotify';
	import { searchResults, notFoundSearchResults, playlistNameStore } from '$lib/stores';
	import NoResult from '$lib/components/NoResult.svelte';
	import ArtistResult from '$lib/components/ArtistResult.svelte';
	import { goto } from '$app/navigation';
	import chunk from 'chunk';
	import AlbumResult from '$lib/components/AlbumResult.svelte';

	let playlistName = $playlistNameStore;
	let results = [];
	let url;
	let openResultIndex;

	$: browser && window.localStorage.setItem('results', JSON.stringify(results));

	$: title = `${playlistName} | Lineup.fun - a Spotify playlist generator`;
	$: console.log($searchResults);
	// $: if (!document.referrer.includes('/search')) {
	// 	goto('/');
	// }
	// $: console.log(document.referrer);

	const generate = async () => {
		const trackUris = await Promise.allSettled(
			$searchResults.map((result) => {
				if (result.type === 'artist') {
					return spotify.getArtistTopTracks(result.id, 'GB').then((resp) => {
						return resp.tracks.map((track) => track.uri);
					});
				} else {
					return spotify.getAlbumTracks(result.id, 'GB').then((resp) => {
						return resp.items.map((track) => track.uri);
					});
				}
			})
		).then((promises) => {
			return promises.map((promise) => {
				if (promise.status === 'fulfilled') {
					return promise.value;
				} else {
					return [];
				}
			});
		});

		console.log(trackUris);

		const user = spotifyUser();

		let playlist;
		let error;

		await spotify
			.createPlaylist(user.id, {
				name: playlistName,
				description: `A playlist generated by Lineup.fun`
			})
			.then((resp) => {
				playlist = resp;
				url = resp.external_urls.spotify;
			})
			.catch((reason) => {
				console.log(reason);
			});

		const chunkedTrackUris = chunk(trackUris.flat(), 100);

		await Promise.allSettled(
			chunkedTrackUris.map((chunk) => {
				return spotify.addTracksToPlaylist(playlist.id, chunk);
			})
		);
	};

	const removeResult = (ev) => {
		const { result } = ev.detail;
		// searchResults.update((results) => deleteresults.filter((r) => r !== result));
	};

	const openResults = (ev) => {
		const { index } = ev.detail;
		openResultIndex = index;
	};

	const startAgain = () => {
		searchResults.set([]);
		notFoundSearchResults.set([]);
		goto('/search');
	};
</script>

<svelte:head>
	<title>{title}</title>
</svelte:head>

<div class="container">
	<div class="results">
		<h1>{playlistName}</h1>

		{#each Object.values($searchResults) as results, i}
			{#if results[0].type == 'artist'}
				<ArtistResult
					{results}
					on:removeResult={removeResult}
					on:openResults={openResults}
					dropdownOpen={i === openResultIndex}
				/>
			{:else if results[0].type == 'album'}
				<!-- <AlbumResult {results} on:removeResult={removeResult} /> -->
			{/if}
		{/each}

		{#if $notFoundSearchResults.length > 0}
			<h3>not found</h3>
		{/if}
		{#each $notFoundSearchResults as query}
			<NoResult {query} />
		{/each}
	</div>
	<div class="buttons">
		{#if url}
			<Button big={true} handleClick={() => (window.location.href = url)}>{playlistName}</Button>
		{:else}
			<Button disabled={Object.keys($searchResults).length === 0} big={true} handleClick={generate}
				>generate</Button
			>
		{/if}
		<Button big={true} handleClick={startAgain}>reset</Button>
		<Footer />
	</div>
</div>

<style>
	.container {
		grid-template-columns: 1fr;
		grid-template-rows: 100% 1fr;

		height: 100vh;
		display: flex;
		flex-direction: column;
		width: 100%;
	}
	h1 {
		margin-top: 5rem;
		font-size: 8rem;
	}

	.results {
		display: flex;
		flex-direction: column;
		width: 100%;
		gap: 2.5rem;
		height: auto;
		padding-bottom: 2rem;
		flex-grow: 1;
		overflow-y: scroll;
	}

	.buttons {
		display: flex;
		justify-content: flex-start;
		align-items: flex-start;

		gap: 2rem;

		width: 100%;
		padding-top: 1rem;
		padding-bottom: 5rem;
		max-width: 100%;
	}

	h3 {
		color: #aaa;
	}

	@media (min-width: 1024px) {
		.container {
			display: grid;
			grid-template-columns: 3fr 1fr;
			grid-template-rows: 1fr;
			gap: 6rem;
			max-height: 100vh;
			height: 100vh;
		}

		.results {
			height: 100vh;
		}

		.buttons {
			padding-top: 6rem;
			padding-bottom: 1rem;

			justify-content: space-between;

			flex-direction: column;
		}
	}
</style>
